### ISSUE TITLE
npm run pack failed

### ISSUE THREAD

**Issue by zcrbb** [lyswhut/lx-music-desktop#172]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**
when I execute `npm run pack`, it will be failed at the last step.

**重现**
重现行为的步骤：
1. npm install
2. npm run pack
3. then failed

**截图**
![image](https://user-images.githubusercontent.com/40193711/78911720-4433b800-7ab9-11ea-9721-c64beca3f40e.png)

**Comment by lyswhut** [comment]
This may be due to the failure to download the electron package.
You can try to manually download [electron-v8.1.1-win32-x64.zip](https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-x64.zip) and [electron-v8.1.1-win32-ia32.zip](https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-ia32.zip) to `%HOMEPATH%\AppData\Local\electron\Cache`
