### ISSUE TITLE
Linux端下载的音乐识别不出专辑图片，作曲家等信息

### ISSUE THREAD

**Issue by Leilei332** [lyswhut/lx-music-desktop#484]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述错误**

Linux端在“小芸音乐”下载完音乐后，音频文件没有专辑图片等信息(以Tobu-Higher)，Windows端没有这个问题：
![](https://gitee.com/xlbilly/lei-pic/raw/master/2021-04-1616-03-15.png)
最新版本1.8.2也有这个问题

**环境：**
  -操作系统及版本：Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
  -软件安装包及版本：1.8.6

**Comment by Leilei332** [comment]
> **解决方案检查**
> 
>     * [x]  我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md)
> 
>     * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&q=))
> 
> 
> **描述错误**
> 
> Linux端在“小芸音乐”下载完音乐后，音频文件没有专辑图片等信息(以Tobu-Higher)，Windows端没有这个问题：
> ![](https://camo.githubusercontent.com/ab7f2f0bb2954c1535baf16518ad63802509c8c34258d12308f5184cc89edb8a/68747470733a2f2f67697465652e636f6d2f786c62696c6c792f6c65692d7069632f7261772f6d61737465722f323032312d30342d313631362d30332d31352e706e67)
> 最新版本1.8.2也有这个问题
> 
> **环境：**
>   -操作系统及版本：Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
>   -软件安装包及版本：1.8.6

**Comment by wanshijixiang** [comment]
我是个新人，我不知道把啥动了，怎么老收到这种github的邮件呀，关键是我发现这收件人不是我呀，我怎么会收到邮件呀，求解答。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月16日(周五) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lyswhut/lx-music-desktop] Linux端下载的音乐识别不出专辑图片，作曲家等信息 (#484)




  
解决方案检查
 * [x]  我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md) * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&amp;q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&amp;q=))  
描述错误
 
Linux端在“小芸音乐”下载完音乐后，音频文件没有专辑图片等信息(以Tobu-Higher)，Windows端没有这个问题：
 
 最新版本1.8.2也有这个问题
 
环境：
 -操作系统及版本：Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
 -软件安装包及版本：1.8.6
  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月16日(周五) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lyswhut/lx-music-desktop] Linux端下载的音乐识别不出专辑图片，作曲家等信息 (#484)




  
解决方案检查
 * [x]  我已阅读常见问题(https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md) * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&amp;q=](https://github.com/lyswhut/lx-music-desktop/issues?utf8=%E2%9C%93&amp;q=))  
描述错误
 
Linux端在“小芸音乐”下载完音乐后，音频文件没有专辑图片等信息(以Tobu-Higher)，Windows端没有这个问题：
 
 最新版本1.8.2也有这个问题
 
环境：
 -操作系统及版本：Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
 -软件安装包及版本：1.8.6

**Comment by lyswhut** [comment]
@wanshijixiang 不想收到所有通知的话，可以修改右上角watch设置：
![image](https://user-images.githubusercontent.com/20365169/114996226-36d1ba80-9ed1-11eb-8c3c-cf436fe5eb8d.png)

**Comment by wanshijixiang** [comment]
哦哦 ，谢谢啦，那可能是我star的时候不小心碰到watch了，哈哈。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月16日(周五) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lyswhut/lx-music-desktop] Linux端下载的音乐识别不出专辑图片，作曲家等信息 (#484)




 
@wanshijixiang 不想收到所有通知的话，可以修改右上角watch设置：
